image: golang:1.15

stages:
  - lint
  - build

before_script:
  - mkdir -p /go/src/hades.it.usyd.edu.au/diablo-benchmark /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/hades.it.usyd.edu.au/diablo-benchmark
  - make reqs

lint_code:
  stage: lint
  script:
    - make lint

build:
  stage: build
  script:
    - make
