bench:
  datapath: workloads/DBW-NASDAQ/premade_data.json
  txs:
    0: 178
    1: 179
    2: 201
    3: 143
    4: 96
    5: 79
    6: 81
    7: 125
    8: 83
    9: 121
    10: 61
    11: 92
    12: 101
    13: 114
    14: 92
    15: 91
    16: 110
    17: 114
    18: 98
    19: 140
    20: 146
    21: 159
    22: 179
    23: 99
    24: 47
    25: 82
    26: 79
    27: 81
    28: 83
    29: 64
  type: premade
contract:
  name: ExchangeContract
  path: workloads/DBW-NASDAQ/contracts/chaincode/exchange.go
description: NASDAQ Top 10 stock trades pulled 2021-01-11
name: NASDAQ Benchmark Configuration (start=3; end=33)
secondaries: 2
threads: 2
