name: "Contention"
description: "Contention-focused workload to showcase design choice of Hyperledger Fabric"
secondaries: 1
threads: 1

bench:
  type: "contention"
  txs:
    0: 20
    1: 20
    2: 20
    3: 20
    4: 20
    5: 20
    6: 20
    7: 20
    8: 20
    9: 20
    10: 20
    11: 20
    12: 20
    13: 20
    14: 20
    15: 20
    16: 20
    17: 20
    18: 20
    19: 20
    20: 20
    21: 20
    22: 20
    23: 20
    24: 20
    25: 20
    26: 20
    27: 20
    28: 20
    29: 20
contract:
  functions:
    - name: "CreateAsset"
      ftype: "write"
      ratio: 80
      params:
        - type: "id"
          value: ""
        - type: "value"
          value: "1"
    - name : "UpdateAsset"
      ftype: "write"
      ratio: 20
      params:
        - type: "id"
          value: ""
        - type: "value"
          value: "1"


