name: "Aviation Parts Online Market Place"
description: "Honeywell inspired Online Market Place"
secondaries: 1
threads: 1

bench:
  type: "aviation"
  txs:
    0: 5
    5: 5
contract:
  functions:
    # standard asset creation
    - name: "CreatePart"
      ftype: "write"
      ratio: 50
      params:
        - type: "partID"
          value: "part#"
        - type: "Description"
          value: ""
        - type: "Certification"
          value: ""
        - type: "owner"
          value: ""
        - type: "price"
          value: "0"
    # rich querying not based on partID, relevant as people query by owner rather than partID
    - name : "QueryPartsByOwner"
      ftype: "read"
      ratio: 25
      params:
        - type: "owner"
          value: ""
    # Transfer of part between owners, will create a purchase order in the chain to enable traceability of objects
    - name : "TransferPart"
      ftype: "write"
      ratio: 25
      params:
        - type: "partID"
          value: "part#"
        - type: "purchaseOrderID"
          value: "purchaseOrder#"
        - type: "newOwner"
          value: ""

