version: '3'

# Global definition for each node
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "quorumengineering/quorum:20.10.0"
  expose:
    - "21000"
    - "50400"
  labels:
    com.quorum.consensus: raft
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/quorumdata/datadir
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cat /nodes/genesis.json
      cp /nodes/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /nodes/keys/key$${NODE_ID} $${DDIR}/keystore/
      cat /nodes/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/nodes/genesis.json"
      NETWORK_ID=10
      GETH_ARGS_raft="--raft --raftport 50400"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --allow-insecure-unlock \
        --identity node$${NODE_ID}-raft \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --rpc \
        --rpccorsdomain "*" \
        --rpcvhosts "*" \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --port 21000 \
        --ws \
        --wsaddr 0.0.0.0 \
        --wsport 8546 \
        --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
        --wsorigins "*" \
        --unlock 0 \
        --password /nodes/passwords.txt \
        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_raft}

# Services for the 7 nodes
services:
  quorum1:
    << : *quorum-def
    hostname: quorum1
    ports:
      - "22000:8545"
      - "22010:8546"
    volumes:
      - ./nodedata:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=1
    networks:
      quorum-net:
        ipv4_address: 172.16.239.11
  quorum2:
    << : *quorum-def
    hostname: quorum2
    ports:
      - "22001:8545"
      - "22011:8546"
    volumes:
      - ./nodedata:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=2
    networks:
      quorum-net:
        ipv4_address: 172.16.239.12
  quorum3:
    << : *quorum-def
    hostname: quorum3
    ports:
      - "22002:8545"
      - "22012:8546"
    volumes:
      - ./nodedata:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=3
    networks:
      quorum-net:
        ipv4_address: 172.16.239.13
  quorum4:
    << : *quorum-def
    hostname: quorum4
    ports:
      - "22003:8545"
      - "22013:8546"
    volumes:
      - ./nodedata:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=4
    networks:
      quorum-net:
        ipv4_address: 172.16.239.14
  quorum5:
    << : *quorum-def
    hostname: quorum5
    ports:
      - "22004:8545"
      - "22014:8546"
    volumes:
      - ./nodedata:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=5
    networks:
      quorum-net:
        ipv4_address: 172.16.239.15
  quorum6:
    << : *quorum-def
    hostname: quorum6
    ports:
      - "22005:8545"
      - "22015:8546"
    volumes:
      - ./nodedata:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=6
    networks:
      quorum-net:
        ipv4_address: 172.16.239.16
  quorum7:
    << : *quorum-def
    hostname: quorum7
    ports:
      - "22006:8545"
      - "22016:8546"
    volumes:
      - ./nodedata:/nodes:ro
    environment:
      - PRIVATE_CONFIG=ignore
      - NODE_ID=7
    networks:
      quorum-net:
        ipv4_address: 172.16.239.17
networks:
  quorum-net:
    name: quorum-net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
